PILOT-5191: update cli with new apikey token refresh workflow
PilotDataPlatform/cli pull request #144
Opened 2024-05-24 20:39 UTC by colorzzr

## Summary

now apikey will return refresh token. Cli no longer needs to call apikey endpoint to refresh access token

## JIRA Issues

PILOT-5191

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2024-06-04 13:37 UTC, vmoshynskyi requested changes
Could you please review my comments? Additionally, there are some leftovers related to `api_key` that should be removed.:
- `keycloak_api_key_audience` field in `Settings`
- `is_api_key` function in `SrvTokenManager`, since we don't use `api-key` audiences anymore.

2024-06-04 13:37 UTC, vmoshynskyi commented on app/services/user_authentication/user_login_logout.py
> +def exchange_api_key(api_key: str) -> Union[Tuple[str, str], None]:
```suggestion
def exchange_api_key(api_key: str) -> Union[Tuple[str, str], Tuple[None, None]]:
```

2024-06-04 13:37 UTC, vmoshynskyi commented on app/services/user_authentication/user_login_logout.py
> +    return response.json()['access_token'], response.json()['refresh_token']
I would suggest to avoid parsing json response twice:
```suggestion
    response = response.json()
    return response['access_token'], response['refresh_token']
```

2024-06-04 13:37 UTC, vmoshynskyi commented on tests/app/commands/test_user.py
> +        f'{AppConfig.Connections.url_keycloak_realm}/api-key/{api_key}', json={'access_token': access_token, 'refresh_token': fake.pystr(20)}
I would suggest to create a refresh token using `jwt` package instead of a random string:
```python
refresh_token = jwt.encode({'typ': 'Refresh'}, key='').decode()
```

Please also add an assertion for `UserConfig` property below:
```python
assert user.refresh_token == refresh_token
```

2024-06-04 13:37 UTC, vmoshynskyi commented on tests/app/services/user_authentication/test_token_manager.py
> +    def test_refresh_calls_refresh_api_key_method_when_is_api_key_method_returns_true(self, requests_mock, fake):
Please update test name, since it's doesn't call `refresh_api_key` method anymore, rather calls refresh token endpoint.

2024-06-05 14:50 UTC, colorzzr commented
> Could you please review my comments? Additionally, there are some leftovers related to `api_key` that should be removed.:
> 
>     * `keycloak_api_key_audience` field in `Settings`
> 
>     * `is_api_key` function in `SrvTokenManager`, since we don't use `api-key` audiences anymore.

Thanks for reviewing!!

2024-06-06 12:06 UTC, vmoshynskyi approved these changes

2024-06-10 14:48 UTC, merged