Pilot 5588: update cli logic to adopt Windows system
PilotDataPlatform/cli pull request #161
Opened 2024-07-22 20:53 UTC by colorzzr

## Summary

with new requirement, now cli will also be executed on Windows machine, which lead to a requirement to test code base with windows adaptability. This PR made following updates to achieve such requirements:
 1. update github actions to build cli binary in windows runner.
 2. update `file upload` command to convert windows path(eg. folder\\file.txt) to object storage path(eg. folder/file.txt).
 3. update poetry file with `extras` section for windows packages.
 4. update configuration file permission with Windows permissions.

## JIRA Issues

PILOT-5588

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes
- [ ] No

## Test Directions

fixup test cases with new updates

2024-07-25 04:46 UTC, erikdvlp approved these changes

2024-07-25 04:46 UTC, erikdvlp commented on app/configs/user_config.py
> +        error = self._check_user_permissions(config_path, (0o0500, 0o0700))
Do you think we should have enum variants for these octal permissions for readability?

2024-08-07 15:42 UTC, colorzzr commented on app/configs/user_config.py
> +        error = self._check_user_permissions(config_path, (0o0500, 0o0700))
Oh yes `Enum` variables give better visual representations. Will update them!

2024-08-08 11:32 UTC, erikdvlp commented on app/configs/user_config.py
> +
```suggestion
```

2024-08-08 13:03 UTC, andricDu requested changes

2024-08-08 13:03 UTC, andricDu commented on .github/workflows/build-and-publish.yml
> +          python-version: 3.9
should we update this to 3.10 now?

2024-08-08 13:13 UTC, colorzzr commented on .github/workflows/build-and-publish.yml
> +          python-version: 3.9
oh yes will update to 3.10.12

2024-08-08 19:42 UTC, andricDu approved these changes

2024-08-08 19:42 UTC, merged